// ============================================================================
// dict.js — GitHub 界面 UI「英 → 中」离线词典
// 设计原则：
//   1. 只收录 GitHub 界面外壳（导航 / 菜单 / 按钮 / 标签 / 计数），
//      绝不收录任何项目正文（README、代码、议题/评论正文、文件名、用户名）。
//   2. EXACT 为「整词精确匹配」（规范化空白 + 大小写不敏感），
//      不做子串替换，避免误伤。
//   3. RULES 仅处理含数字的固定 UI 句式（如 "12 Open"、"34 stars"），
//      全部首尾锚定。
// 本文件先于 content.js 注入，向 isolated world 暴露 window.__GH_UI_DICT__。
// 想增补词条：直接往 EXACT 里加 "english": "中文" 即可，无需改动其它文件。
// ============================================================================
(function () {
  "use strict";

  const EXACT = {
    // ==== 新增：评论框工具条（真实登录态采集） ====
    "bold": "加粗",
    "italic": "斜体",
    "heading": "标题",
    "quote": "引用",
    "link": "链接",
    "numbered list": "编号列表",
    "unordered list": "项目符号列表",
    "task list": "任务列表",
    "reference": "引用编号",
    "paste, drop, or click to add files": "粘贴、拖放或点击以添加文件",
    "agents": "智能体",
    "retry": "重试",
    "dismiss error": "忽略错误",
    "more items": "更多项目",
    "close dialog": "关闭对话框",
    "close menu": "关闭菜单",
    "open menu": "打开菜单",
    "open user navigation menu": "打开用户导航菜单",
    "homepage": "主页",
    "menu": "菜单",
    "reload": "重新加载",
    "hide comment": "隐藏评论",
    "dependabot commands and options": "Dependabot 命令与选项",
    "release notes": "发布说明",
    "verified": "已验证",
    // ==== 新增：通知（真实登录态采集） ====
    "all issues": "全部议题",
    "all repositories": "全部仓库",
    "chat with copilot": "与 Copilot 聊天",
    "clear out the clutter.": "清走积压事项。",
    "mark all read notifications as done": "将全部已读通知标记为完成",
    "mark as done": "标记为完成",
    "mark as read": "标记为已读",
    "mark as unread": "标记为未读",
    "you have unread notifications": "你有未读通知",
    "mention": "提及",
    "state change": "状态变更",
    // ==== 新增：设置（真实登录态采集） ====
    "accessibility": "辅助功能",
    "account settings": "账户设置",
    "additional billing details": "附加账单信息",
    "ai usage": "AI 用量",
    "archives": "归档",
    "are you sure you want to do this?": "确定要执行此操作吗？",
    "available for hire": "接受工作邀约",
    "billing and licensing": "账单与许可",
    "bio": "个人简介",
    "blocked users": "已屏蔽的用户",
    "budgets and alerts": "预算与提醒",
    "cancel plan and delete this account": "取消订阅并删除此账户",
    "change my username": "更改我的用户名",
    "change username": "更改用户名",
    "cloud agent": "云端智能体",
    "code review limits": "代码审查限额",
    "code security": "代码安全",
    "code, planning, and automation": "代码、规划与自动化",
    "company": "公司",
    "contributions & activity": "贡献与动态",
    "create a new saved reply": "新建常用回复",
    "credentials": "凭据",
    "delete account": "删除账户",
    "delete your account": "删除你的账户",
    "display current local time": "显示当前本地时间",
    "education benefits": "教育优惠",
    "enter a new username": "输入新用户名",
    "enterprises": "企业",
    "export account data": "导出账户数据",
    "github developer program": "GitHub 开发者计划",
    "include private contributions on my profile": "在我的主页上包含私密贡献",
    "interaction limits": "互动限制",
    "jobs profile": "求职资料",
    "learn more about hiding comments": "了解隐藏评论的更多事宜",
    "licensing": "许可",
    "location": "所在地",
    "make profile private and hide activity": "将主页设为私密并隐藏动态",
    "payment history": "付款历史",
    "payment information": "付款信息",
    "preferred spoken language": "常用口语",
    "profile picture": "头像",
    "profile settings": "资料设置",
    "pronouns": "代词",
    "public email": "公开邮箱",
    "public profile": "公开主页",
    "really change your username?": "确定要更改用户名吗？",
    "save jobs profile": "保存求职资料",
    "scheduled reminders": "定时提醒",
    "search by username, full name, or email address": "按用户名、姓名或邮箱地址搜索",
    "security log": "安全日志",
    "settings menu": "设置菜单",
    "show achievements on my profile": "在我的主页上展示成就",
    "social accounts": "社交账号",
    "sponsorship log": "赞助记录",
    "successor settings": "继任者设置",
    "the reason will be displayed to describe this comment to others.": "该原因会显示给其他人，用于说明这条评论。",
    "time zone": "时区",
    "trending settings": "热门设置",
    "update preferences": "更新偏好设置",
    "update profile": "更新资料",
    "upload a photo…": "上传照片…",
    "usage": "用量",
    "your username or email:": "你的用户名或邮箱：",
    // ==== 新增：PR与评论（真实登录态采集） ====
    "add files": "添加文件",
    "add or remove reactions": "添加或移除表情回应",
    "add this suggestion to a batch that can be applied as a single commit.": "把此建议加入可作为一个提交批量应用的列表。",
    "add your comment here...": "在此添加你的评论……",
    "an unexpected error has occurred": "发生意外错误",
    "applies to this pull request for everyone.": "对本拉取请求的所有人生效。",
    "applying suggestions on deleted lines is not supported.": "不支持在已删除的行上应用建议。",
    "ask admin for access": "向管理员申请权限",
    "attach files": "附加文件",
    "attaching documents requires write permission to this repository.": "附加文档需要此仓库的写入权限。",
    "choose a reason": "选择原因",
    "choose a reason for hiding this comment": "选择隐藏此评论的原因",
    "code owner review required by reviewers with write access.": "需要有写入权限的代码所有者审查。",
    "coming soon": "即将推出",
    "copilot review effort, defaults to balanced": "Copilot 审查强度，默认为均衡",
    "copy head branch name to clipboard": "复制头分支名到剪贴板",
    "deep analysis, moderate cost": "深度分析，成本中等",
    "dismiss alert": "忽略提示",
    "efficient review, low cost": "高效审查，成本低",
    "learn about draft prs": "了解草稿拉取请求",
    "learn more about copilot code review.": "了解 Copilot 代码审查的更多信息。",
    "low quality": "低质量",
    "merge info": "合并信息",
    "most thorough, high cost": "最彻底，成本高",
    "negative feedback": "负面反馈",
    "off topic": "偏离主题",
    "only one suggestion per line can be applied in a batch.": "每行只能有一条建议被批量应用。",
    "open in a new github.dev tab": "在新标签页打开 github.dev",
    "open in codespace": "在 codespace 中打开",
    "open in github.dev": "在 github.dev 中打开",
    "outdated": "已过时",
    "outdated suggestions cannot be applied.": "已过时的建议无法应用。",
    "please reload this page": "请重新加载此页面",
    "positive feedback": "正面反馈",
    "remember, contributions to this repository should follow its": "请记住，向此仓库贡献内容应遵守其",
    "repository navigation": "仓库导航",
    "select a reply": "选择常用回复",
    "slash commands": "斜杠命令",
    "still in progress?": "还在进行中吗？",
    "successfully merging this pull request may close these issues.": "成功合并此拉取请求可能会关闭以下议题。",
    "suggestion cannot be applied right now. please check back later.": "此建议目前无法应用，请稍后再试。",
    "suggestions cannot be applied from pending reviews.": "待提交审查中的建议无法应用。",
    "suggestions cannot be applied on multi-line comments.": "多行评论中的建议无法应用。",
    "suggestions cannot be applied while the pull request is closed.": "拉取请求已关闭，无法应用建议。",
    "suggestions cannot be applied while viewing a subset of changes.": "正在查看部分更改，无法应用建议。",
    "switch repository": "切换仓库",
    "there was a problem hiding this comment.": "隐藏此评论时出现问题。",
    "there was an error while loading.": "加载时出错。",
    "this branch has not been deployed": "此分支尚未部署",
    "this file is empty.": "此文件为空。",
    "this file is hidden.": "此文件已隐藏。",
    "this suggestion has been applied or marked resolved.": "此建议已应用或已标记为已解决。",
    "this suggestion is invalid because no changes were made to the code.": "此建议无效，因为代码没有任何改动。",
    "try again with a file that’s not empty.": "请换一个非空文件再试。",
    "try again with another file.": "请换一个文件再试。",
    "view reviewed changes": "查看已审查的更改",
    "view session": "查看会话",
    "view status": "查看状态",
    "we don’t support that file type.": "我们不支持该文件类型。",
    "you can’t perform that action at this time.": "你目前无法执行该操作。",
    "you signed in with another tab or window.": "你在另一个标签页或窗口中登录了。",
    "you signed out in another tab or window.": "你在另一个标签页或窗口中登出了。",
    "you switched accounts on another tab or window.": "你在另一个标签页或窗口中切换了账户。",
    "contributing guidelines": "贡献指南",
    "code of conduct": "行为准则",
    "security policy": "安全政策",
    "left a comment": "留下了评论",
    "marked this pull request as ready for review": "已将此拉取请求标记为可供审查",
    "mentioned this pull request": "提到了此拉取请求",
    "abuse": "滥用",
    "duplicate": "重复",
    "resolved": "已解决",
    "spam": "垃圾内容",
    "owner": "所有者",
    "edited": "已编辑",
    // ==== 新增：通知页（真实登录态采集） ====
    "manage notifications": "管理通知",
    "notification settings": "通知设置",
    "watched repositories": "已关注的仓库",
    "subscriptions": "订阅",
    "inbox": "收件箱",
    "switch inbox": "切换收件箱",
    "saved": "已保存",
    "filters": "筛选器",
    "assigned": "指派给我",
    "participating": "我参与的",
    "mentioned": "提及我的",
    "team mentioned": "团队被提及",
    "review requested": "请求审查",
    "folders": "文件夹",
    "add new filter": "添加筛选器",
    "all": "全部",
    "unread": "未读",
    "search notifications": "搜索通知",
    "sort by:": "排序：",
    "group by:": "分组：",
    "newest to oldest": "最新在前",
    "oldest to newest": "最早在前",
    "date": "日期",
    "repository": "仓库",
    "get started": "开始使用",
    "clean up your inbox": "清理收件箱",
    "notifications by date": "按日期分组的通知",
    "single sign-on": "单点登录",
    "select all": "全选",
    "prev": "上一页",

    // ==== 新增：控制台 / 首页（真实登录态采集） ====
    "trending repositories": "热门仓库",
    "recommended for you": "为你推荐",
    "show less activity like this": "少显示此类动态",
    "feed": "动态",
    "announcements": "公告",
    "update posts from repositories": "仓库更新帖",
    "repository activity": "仓库活动",
    "follows": "关注动态",
    "who people are following": "大家在关注谁",
    "recommendations": "推荐",
    "reset to default": "恢复默认",
    "send feedback": "发送反馈",
    "lists": "列表",
    "create list": "创建列表",
    "chat commands": "聊天命令",
    "create issue": "创建议题",
    "write code": "编写代码",

    // ==== 新增：议题 / PR 详情页 ====
    "no milestone": "无里程碑",
    "no deployments": "无部署",
    "sign in to comment": "登录后评论",
    "copilot code review": "Copilot 代码审查",

    // ==== 新增：PR / 议题列表界面 ====
    "all pull requests": "全部拉取请求",
    "search pull requests": "搜索拉取请求",
    "milestones": "里程碑",
    "reviews": "审查",
    "sort by": "排序方式",
    "newest": "最新",
    "oldest": "最早",
    "recently updated": "最近更新",
    "ascending": "升序",
    "descending": "降序",
    "member": "成员",
    "contributor": "贡献者",
    "bot": "机器人",
    "review required": "需要审查",
    "issue types": "议题类型",

    // ==== 新增：全站顶栏 ====
    "platform": "平台",
    "solutions": "解决方案",
    "resources": "资源",
    "enterprise": "企业",
    "open source": "开源",
    "pricing": "定价",
    "documentation": "文档",
    "blog": "博客",
    "changelog": "更新日志",
    "why github": "为什么选择 GitHub",
    "customer stories": "客户案例",
    "community forum": "社区论坛",
    "partners": "合作伙伴",
    "trust center": "信任中心",
    "customer support": "客户支持",
    "view all features": "查看全部功能",
    "view all solutions": "查看全部解决方案",
    "view all use cases": "查看全部用例",
    "view all industries": "查看全部行业",
    "view all topics": "查看全部主题",
    "view all resources": "查看全部资源",
    "topics": "主题",
    "trending": "热门",
    "collections": "合集",
    "security lab": "安全实验室",
    "maintainer community": "维护者社区",
    "archive program": "归档计划",
    "enterprise platform": "企业平台",
    "premium support": "高级支持",
    "copilot for business": "Copilot 商业版",
    "ai-powered developer platform": "AI 驱动的开发者平台",
    "enterprise-grade security features": "企业级安全功能",
    "enterprise-grade ai features": "企业级 AI 功能",
    "enterprise-grade 24/7 support": "企业级 7×24 支持",
    "fund open source developers": "资助开源开发者",
    "skip to content": "跳到主要内容",
    "navigation menu": "导航菜单",
    // ==== 新增：顶栏分组小标题 ====
    "ai code creation": "AI 代码编写",
    "developer workflows": "开发者工作流",
    "application security": "应用安全",
    "by company size": "按公司规模",
    "by use case": "按用例",
    "by industry": "按行业",
    "explore by topic": "按主题浏览",
    "explore by type": "按类型浏览",
    "support & services": "支持与服务",
    "community": "社区",
    "programs": "计划",
    "enterprise solutions": "企业解决方案",
    "available add-ons": "可选增值包",
    // ==== 新增：仓库页界面 ====
    "public": "公开",
    "private": "私有",
    "starred": "已加星标",
    "forked": "已派生",
    "folders and files": "文件夹与文件",
    "name": "名称",
    "last commit message": "最后提交信息",
    "last commit date": "最后提交日期",
    "security and quality": "安全与质量",
    "view all files": "查看全部文件",
    "repository files navigation": "仓库文件导航",
    "items": "项",
    "watchers": "关注者",
    "watching": "正在关注",
    "no releases published": "尚未发布任何版本",
    // ==== 新增：页脚 ====
    "footer": "页脚",
    "footer navigation": "页脚导航",
    "terms": "条款",
    "privacy": "隐私",
    "status": "服务状态",
    "docs": "文档",
    "contact": "联系我们",
    "manage cookies": "管理 Cookie",
    "do not share my personal information": "不要共享我的个人信息",

    // ---- 顶部全局导航 / 账户菜单 ----
    "pull requests": "拉取请求",
    "issues": "议题",
    "marketplace": "应用市场",
    "explore": "探索",
    "search": "搜索",
    "dashboard": "控制台",
    "notifications": "通知",
    "sign in": "登录",
    "sign up": "注册",
    "sign out": "退出登录",
    "create repository": "新建仓库",
    "new repository": "新建仓库",
    "new gist": "新建代码片段",
    "new organization": "新建组织",
    "new project": "新建项目",
    "import repository": "导入仓库",
    "your profile": "你的主页",
    "your repositories": "你的仓库",
    "your codespaces": "你的 Codespaces",
    "your gists": "你的代码片段",
    "your organizations": "你的组织",
    "your enterprises": "你的企业",
    "your projects": "你的项目",
    "your stars": "你的星标",
    "settings": "设置",
    "sponsors": "赞助",

    // ---- 仓库页一级标签（UnderlineNav / reponav）----
    "code": "代码",
    "actions": "操作",
    "projects": "项目",
    "security": "安全",
    "insights": "洞察",
    "discussions": "讨论",
    "releases": "发布",
    "packages": "包",
    "environments": "环境",
    "deployments": "部署",
    "branches": "分支",
    "tags": "标签",

    // ---- 仓库首页 / 侧栏 ----
    "about": "关于",
    "star": "星标",
    "stars": "星标",
    "fork": "派生",
    "forks": "派生",
    "watch": "关注",
    "unwatch": "取消关注",
    "used by": "使用者",
    "contributors": "贡献者",
    "languages": "语言",
    "top languages": "主要语言",
    "activity": "动态",
    "customize your pins": "自定义置顶",
    "release": "发布",
    "latest": "最新",
    "latest release": "最新发布",
    "no releases": "暂无发布",
    "no packages": "暂无包",
    "no environments": "暂无环境",
    "view all": "查看全部",
    "sponsor": "赞助",
    "report repository": "举报此仓库",

    // ---- 代码浏览 ----
    "go to file": "转到文件",
    "add file": "添加文件",
    "clone": "克隆",
    "download zip": "下载 ZIP",
    "open with github desktop": "用 GitHub Desktop 打开",
    "open on github desktop": "在 GitHub Desktop 打开",
    "latest commit": "最新提交",
    "last commit": "最近提交",
    "history": "历史记录",
    "permalink": "永久链接",
    "blame": "追溯",
    "raw": "原始",
    "edit this file": "编辑此文件",
    "delete this file": "删除此文件",
    "upload files": "上传文件",
    "create new file": "新建文件",
    "fork this repository and propose changes": "派生此仓库并提议更改",
    "copy": "复制",
    "copied!": "已复制！",
    "copy raw file contents": "复制原始文件内容",
    "copy file path": "复制文件路径",
    "lines": "行",
    "executable file": "可执行文件",
    "jump to": "跳转到",
    "view blame": "查看追溯",
    "view raw": "查看原始",
    "file metadata": "文件元数据",
    "files": "文件",
    "repository files": "仓库文件",
    "filter files": "筛选文件",

    // ---- Issue / Pull request ----
    "open": "开启",
    "closed": "已关闭",
    "merged": "已合并",
    "draft": "草稿",
    "close issue": "关闭议题",
    "close pull request": "关闭拉取请求",
    "close with comment": "评论并关闭",
    "reopen": "重新打开",
    "reopen issue": "重新打开议题",
    "reopen pull request": "重新打开拉取请求",
    "comment": "评论",
    "comments": "评论",
    "add a comment": "添加评论",
    "write": "编辑",
    "preview": "预览",
    "assignees": "指派者",
    "assignee": "指派者",
    "labels": "标签",
    "label": "标签",
    "milestone": "里程碑",
    "development": "开发",
    "linked issues": "关联议题",
    "new issue": "新建议题",
    "new pull request": "新建拉取请求",
    "open pull request": "发起拉取请求",
    "merge pull request": "合并拉取请求",
    "confirm merge": "确认合并",
    "create a merge commit": "创建合并提交",
    "squash and merge": "压缩并合并",
    "rebase and merge": "变基并合并",
    "conversation": "对话",
    "commits": "提交",
    "checks": "检查",
    "files changed": "更改的文件",
    "reviewers": "审查者",
    "reviewer": "审查者",
    "review": "审查",
    "approve": "批准",
    "approved": "已批准",
    "request changes": "请求修改",
    "changes requested": "已请求修改",
    "submit review": "提交审查",
    "resolve conversation": "解决对话",
    "show resolved": "显示已解决",
    "all reactions": "全部表情回应",
    "copy link": "复制链接",
    "quote reply": "引用回复",
    "reference in new issue": "在新议题中引用",
    "edit": "编辑",
    "delete": "删除",
    "hide": "隐藏",
    "report content": "举报内容",
    "author": "作者",
    "participants": "参与者",
    "no one assigned": "未指派任何人",
    "none yet": "暂无",
    "filter": "筛选",
    "sort": "排序",
    "lock conversation": "锁定对话",
    "unlock conversation": "解锁对话",
    "convert to draft": "转为草稿",
    "ready for review": "准备就绪，可供审查",
    "mark as draft": "标记为草稿",
    "allow edits by maintainers": "允许维护者编辑",
    "requested reviewers": "已请求的审查者",
    "all checks have passed": "所有检查已通过",
    "some checks were not successful": "部分检查未通过",
    "this branch has no conflicts with the base branch": "此分支与基础分支无冲突",
    "the branch is up to date": "分支已是最新",

    // ---- Discussions 讨论 ----
    "categories": "分类",
    "answered": "已回答",
    "unanswered": "未回答",
    "ask a question": "提问",
    "share": "分享",
    "upvote": "赞同",
    "pin discussion": "置顶讨论",

    // ---- Actions 操作 ----
    "workflows": "工作流",
    "runs": "运行记录",
    "new workflow": "新建工作流",
    "set up a workflow yourself": "自行设置工作流",
    "re-run all jobs": "重新运行所有作业",
    "re-run failed jobs": "重新运行失败的作业",
    "cancel workflow": "取消工作流",
    "jobs": "作业",
    "artifacts": "产物",

    // ---- Security 安全 ----
    "code scanning alerts": "代码扫描警报",
    "secret scanning alerts": "密钥扫描警报",
    "advisories": "安全公告",
    "policy": "策略",

    // ---- Insights 洞察 ----
    "traffic": "流量",
    "code frequency": "代码频率",
    "dependency graph": "依赖关系图",
    "network": "网络",
    "network graph": "网络图",
    "pulse": "动态概览",
    "forks network": "派生网络",

    // ---- Projects 项目 ----
    "board": "看板",
    "table": "表格",
    "roadmap": "路线图",
    "add item": "添加项",

    // ---- 个人主页 ----
    "follow": "关注",
    "unfollow": "取消关注",
    "block or report user": "屏蔽或举报用户",
    "pinned": "置顶",
    "popular repositories": "热门仓库",
    "top repositories": "热门仓库",
    "repositories": "仓库",
    "contribution activity": "贡献动态",
    "overview": "概览",
    "followers": "粉丝",
    "following": "关注中",
    "achievements": "成就",
    "highlights": "亮点",
    "organizations": "组织",

    // ---- Settings 设置 ----
    "profile": "个人资料",
    "account": "账户",
    "appearance": "外观",
    "billing and plans": "账单与方案",
    "developer settings": "开发者设置",
    "save": "保存",
    "update": "更新",
    "cancel": "取消",
    "danger zone": "危险操作区",
    "password and authentication": "密码与认证",
    "sessions": "会话",
    "emails": "邮箱",
    "ssh and gpg keys": "SSH 与 GPG 密钥",
    "saved replies": "常用回复",
    "applications": "应用",
    "personal access tokens": "个人访问令牌",

    // ---- 通用按钮 / 动作 ----
    "confirm": "确认",
    "create": "创建",
    "submit": "提交",
    "continue": "继续",
    "back": "返回",
    "next": "下一步",
    "done": "完成",
    "loading": "加载中",
    "dismiss": "忽略",
    "learn more": "了解更多",
    "show more": "显示更多",
    "show all": "显示全部",
    "view": "查看",
    "add": "添加",
    "remove": "移除",
    "manage": "管理",
    "configure": "配置",
    "enable": "启用",
    "disable": "禁用",
    "yes": "是",
    "no": "否",
    "ok": "确定",
    "save changes": "保存更改",
    "discard": "放弃",
    "discard changes": "放弃更改",
    "rename": "重命名",
    "transfer": "转移",
    "archive": "归档",
    "load more": "加载更多",
    "expand all": "全部展开",
    "collapse all": "全部折叠",
    "regenerate": "重新生成",
    "try again": "重试",
    "refresh": "刷新",
    "close": "关闭",
    "apply": "应用",
    "reset": "重置",
    "options": "选项",
    "details": "详情",
    "more": "更多",
    "show less": "收起"
  };

  // 数字 token：12 / 1,234 / 1.2k / 3M
  const N = "(\\d[\\d.,]*\\s*[kKmM]?)";

  const RULES = [
    [new RegExp("^" + N + "\\s+open$"), "$1 开启"],
    [new RegExp("^" + N + "\\s+closed$"), "$1 已关闭"],
    [new RegExp("^" + N + "\\s+merged$"), "$1 已合并"],
    [new RegExp("^" + N + "\\s+stars?$"), "$1 星标"],
    // 「N forks」必须与 EXACT 里的 fork/forks=派生 同词，否则同一页面出现「派生 / 复刻」两种译法
    [new RegExp("^" + N + "\\s+forks?$"), "$1 派生"],
    [new RegExp("^" + N + "\\s+watchers?$"), "$1 关注者"],
    [new RegExp("^" + N + "\\s+followers?$"), "$1 粉丝"],
    [new RegExp("^" + N + "\\s+following$"), "$1 关注中"],
    [new RegExp("^" + N + "\\s+comments?$"), "$1 评论"],
    [new RegExp("^" + N + "\\s+commits?$"), "$1 提交"],
    [new RegExp("^" + N + "\\s+branches?$"), "$1 分支"],
    [new RegExp("^" + N + "\\s+tags?$"), "$1 标签"],
    [new RegExp("^" + N + "\\s+releases?$"), "$1 发布"],
    [new RegExp("^" + N + "\\s+packages?$"), "$1 包"],
    [new RegExp("^" + N + "\\s+contributors?$"), "$1 贡献者"],
    [new RegExp("^" + N + "\\s+discussions?$"), "$1 讨论"],
    [/^line\s+(\d+)$/i, "第 $1 行"]
  ];

  // 小写 key 表（大小写不敏感）
  const lowerMap = Object.create(null);
  for (const key of Object.keys(EXACT)) {
    lowerMap[key.toLowerCase()] = EXACT[key];
  }

  function normalize(text) {
    return String(text).replace(/\s+/g, " ").trim();
  }

  function lookup(rawText) {
    const text = normalize(rawText);
    if (!text) return null;
    const key = text.toLowerCase();
    if (Object.prototype.hasOwnProperty.call(lowerMap, key)) {
      return lowerMap[key];
    }
    for (const [re, rep] of RULES) {
      if (re.test(key)) {
        return key.replace(re, rep);
      }
    }
    return null;
  }

  // 暴露给 content.js
  window.__GH_UI_DICT__ = { lookup, normalize, size: Object.keys(EXACT).length };
})();
